[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83b93ec130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83b93ecf40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83b93ecdc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /wd/hub/session